"""add unique constraint to account name and owner

Revision ID: 1cfc96a9c528
Revises: e9a40d767154
Create Date: 2026-02-08 20:05:41.821361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfc96a9c528'
down_revision: Union[str, Sequence[str], None] = 'e9a40d767154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Handle existing duplicates before applying constraint
    conn = op.get_bind()
    
    # Identify duplicates and re-link transactions to the 'first' account (lowest ID)
    # 1. Update transactions (account_id)
    conn.execute(sa.text("""
        WITH keepers AS (
            SELECT DISTINCT ON (name, owner_id) id, name, owner_id
            FROM accounts
            ORDER BY name, owner_id, id
        ),
        duplicates AS (
            SELECT a.id as dup_id, k.id as keeper_id
            FROM accounts a
            JOIN keepers k ON a.name = k.name AND a.owner_id = k.owner_id
            WHERE a.id != k.id
        )
        UPDATE transactions
        SET account_id = duplicates.keeper_id
        FROM duplicates
        WHERE transactions.account_id = duplicates.dup_id;
    """))

    # 2. Update transactions (destination_account_id for transfers)
    conn.execute(sa.text("""
        WITH keepers AS (
            SELECT DISTINCT ON (name, owner_id) id, name, owner_id
            FROM accounts
            ORDER BY name, owner_id, id
        ),
        duplicates AS (
            SELECT a.id as dup_id, k.id as keeper_id
            FROM accounts a
            JOIN keepers k ON a.name = k.name AND a.owner_id = k.owner_id
            WHERE a.id != k.id
        )
        UPDATE transactions
        SET destination_account_id = duplicates.keeper_id
        FROM duplicates
        WHERE transactions.destination_account_id = duplicates.dup_id;
    """))

    # 3. Delete the duplicate accounts
    conn.execute(sa.text("""
        DELETE FROM accounts
        WHERE id IN (
            SELECT a.id
            FROM accounts a
            LEFT JOIN (
                SELECT DISTINCT ON (name, owner_id) id
                FROM accounts
                ORDER BY name, owner_id, id
            ) k ON a.id = k.id
            WHERE k.id IS NULL
        );
    """))

    # Now we can safely apply the unique constraint
    op.create_unique_constraint('uq_account_name_owner', 'accounts', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_name_owner', 'accounts', type_='unique')
    # ### end Alembic commands ###
