"""add_financial_aggregation_tables

Revision ID: 26c7dc11cfa1
Revises: 85791435df9f
Create Date: 2026-05-26 06:15:01.273728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c7dc11cfa1'
down_revision: Union[str, Sequence[str], None] = '85791435df9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('consent_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_connections_user_id'), 'data_source_connections', ['user_id'], unique=False)
    op.create_table('aggregated_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('invested_value', sa.Float(), nullable=True),
    sa.Column('returns_absolute', sa.Float(), nullable=True),
    sa.Column('returns_percentage', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_source_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_assets_user_id'), 'aggregated_assets', ['user_id'], unique=False)
    op.alter_column('investments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_investments_type', table_name='investments')
    op.drop_index('ix_investments_user_id', table_name='investments')
    op.alter_column('loans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_net_worth_snapshots_snapshot_date', table_name='net_worth_snapshots')
    op.drop_index('ix_net_worth_snapshots_user_id', table_name='net_worth_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_net_worth_snapshots_user_id', 'net_worth_snapshots', ['user_id'], unique=False)
    op.create_index('ix_net_worth_snapshots_snapshot_date', 'net_worth_snapshots', ['snapshot_date'], unique=False)
    op.alter_column('loans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_investments_user_id', 'investments', ['user_id'], unique=False)
    op.create_index('ix_investments_type', 'investments', ['type'], unique=False)
    op.alter_column('investments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_aggregated_assets_user_id'), table_name='aggregated_assets')
    op.drop_table('aggregated_assets')
    op.drop_index(op.f('ix_data_source_connections_user_id'), table_name='data_source_connections')
    op.drop_table('data_source_connections')
    # ### end Alembic commands ###
