"""add subject_match_pattern to account_sync_configs

Revision ID: e649ec2713bf
Revises: 7410b9e37ed2
Create Date: 2026-03-06 23:55:34.896522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e649ec2713bf'
down_revision: Union[str, Sequence[str], None] = '7410b9e37ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_sync_configs', sa.Column('subject_match_pattern', sa.String(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_sync_configs', 'subject_match_pattern')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
